const authConstants = {
    LOGIN_REQUEST: 'LOGIN_REQUEST',
    LOGIN_FAILURE: 'LOGIN_FAILURE',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGOUT_REQUEST: 'LOGOUT_REQUEST',
    LOGOUT_SUCCESS: 'LOGOUT_SUCCESS',
    LOGOUT_FAILURE: 'LOGOUT_FAILURE',
}

const registerConstants = {
    REGISTER_REQUEST: 'REGISTER_REQUEST',
    REGISTER_FAILURE: 'REGISTER_FAILURE',
    REGISTER_SUCCESS: 'REGISTER_SUCCESS'
}

const userInfoConstants = {
    USER_INFO_REQUEST: 'USER_INFO_REQUEST',
    USER_INFO_FAILURE: 'USER_INFO_FAILURE',
    USER_INFO_SUCCESS: 'USER_INFO_SUCCESS'
}

const venueConstants = {
    GETALL_VENUES_REQUEST: 'GETALL_VENUES_REQUEST',
    GETALL_VENUES_SUCCESS: 'GETALL_VENUES_SUCCESS',
    GETALL_VENUES_FAILURE: 'GETALL_VENUES_FAILURE',

    GETONE_VENUE_REQUEST: 'GETONE_VENUE_REQUEST',
    GETONE_VENUE_FAILURE: 'GETONE_VENUE_FAILURE',
    GETONE_VENUE_SUCCESS: 'GETONE_VENUE_SUCCESS',

    GETALL_VENUES_OF_DEALER_REQUEST: 'GETALL_VENUES_OF_DEALER_REQUEST',
    GETALL_VENUES_OF_DEALER_FAILURE: 'GETALL_VENUES_OF_DEALER_FAILURE',
    GETALL_VENUES_OF_DEALER_SUCCESS: 'GETALL_VENUES_OF_DEALER_SUCCESS'
}

const addVenueConstants = {
    ADD_VENUE_REQUEST: 'ADD_VENUE_REQUEST',
    ADD_VENUE_FAILURE: 'ADD_VENUE_FAILURE',
    ADD_VENUE_SUCCESS: 'ADD_VENUE_SUCCESS',
}

const checkoutConstants = {
    CHECKOUT_REQUEST: 'CHECKOUT_REQUEST',
    CHECKOUT_FAILURE: 'CHECKOUT_FAILURE',
    CHECKOUT_SUCCESS: 'CHECKOUT_SUCCESS'
}

const dealsConstants = {
    GET_DEALS_REQUEST: 'DEALS_REQUEST',
    GET_DEALS_FAILURE: 'DEALS_FAILURE',
    GET_DEALS_SUCCESS: 'DEALS_SUCCESS'
}

const serverConstants = {
    SERVER_OFFLINE: 'SERVER_OFFLINE'
}

export {
    authConstants,
    registerConstants,
    userInfoConstants,
    venueConstants,
    addVenueConstants,
    checkoutConstants,
    dealsConstants,
    serverConstants
}

