const authConstants = {
    LOGIN_REQUEST: 'LOGIN_REQUEST',
    LOGIN_FAILURE: 'LOGIN_FAILURE',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGOUT_REQUEST: 'LOGOUT_REQUEST',
    LOGOUT_SUCCESS: 'LOGOUT_SUCCESS',
    LOGOUT_FAILURE: 'LOGOUT_FAILURE',
}

const registerConstants = {
    REGISTER_REQUEST: 'REGISTER_REQUEST',
    REGISTER_FAILURE: 'REGISTER_FAILURE',
    REGISTER_SUCCESS: 'REGISTER_SUCCESS'
}

const userInfoConstants = {
    USER_INFO_REQUEST: 'USER_INFO_REQUEST',
    USER_INFO_FAILURE: 'USER_INFO_FAILURE',
    USER_INFO_SUCCESS: 'USER_INFO_SUCCESS'
}

export {
    authConstants,
    registerConstants,
    userInfoConstants
}

